import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Rejection from "../src/features/rejection";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rejection App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Rejection />
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
